// src/components/levels/LevelsFilters.jsx
"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";

const boxStyle = {
  border: "1px solid #e5e7eb",
  borderRadius: 12,
  padding: 16,
  background: "#f9fafb",
  display: "flex",
  flexDirection: "column",
  gap: 12,
};

const rowStyle = {
  display: "flex",
  flexWrap: "wrap",
  gap: 12,
};

const labelStyle = {
  fontSize: 13,
  fontWeight: 600,
};

const inputStyle = {
  padding: "6px 10px",
  borderRadius: 8,
  border: "1px solid #d1d5db",
  fontSize: 14,
};

export default function LevelsFilters() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const q = searchParams.get("q") ?? "";
  const generatedBy = searchParams.get("generatedBy") ?? "";
  const minLikes = searchParams.get("minLikes") ?? "";
  const authorId = searchParams.get("authorId") ?? "";
  const sort = searchParams.get("sort") ?? "recent";
  const limit = searchParams.get("limit") ?? "20";

  const operatorsParam = searchParams.get("operators") ?? "";
  const selectedOps = operatorsParam ? operatorsParam.split(",") : [];

  // Updates a single query parameter and removes the cursor whenever
  // any filter changes, in order to reset pagination.
  function updateParam(key, value) {
    const sp = new URLSearchParams(searchParams.toString());

    if (value == null || value === "" || (Array.isArray(value) && value.length === 0)) {
      sp.delete(key);
    } else {
      sp.set(key, value);
    }

    // Reset cursor when filters change.
    if (key !== "cursor") sp.delete("cursor");

    const qs = sp.toString();
    router.push(qs ? `${pathname}?${qs}` : pathname, { scroll: false });
  }

  // Toggles an operator in the "operators" query parameter,
  // storing the selected ones as a comma-separated list.
  function toggleOperator(op) {
    const set = new Set(selectedOps);
    if (set.has(op)) set.delete(op);
    else set.add(op);
    const arr = Array.from(set);
    updateParam("operators", arr.length ? arr.join(",") : "");
  }

  // Clears all filters by navigating to the base pathname with no query.
  function clearFilters() {
    router.push(pathname, { scroll: false });
  }

  return (
    <section aria-label="Level filters" style={boxStyle}>
      <div style={rowStyle}>
        <div style={{ flex: "1 1 200px", minWidth: 200 }}>
          <label style={labelStyle}>
            Search
            <input
              style={{ ...inputStyle, width: "100%", marginTop: 4 }}
              type="text"
              placeholder="Title or author..."
              value={q}
              onChange={(e) => updateParam("q", e.target.value)}
            />
          </label>
        </div>

        <div style={{ flex: "0 0 150px" }}>
          <label style={labelStyle}>
            Generated by
            <select
              style={{ ...inputStyle, width: "100%", marginTop: 4 }}
              value={generatedBy}
              onChange={(e) => updateParam("generatedBy", e.target.value)}
            >
              <option value="">All</option>
              <option value="algorithm">Algorithm</option>
              <option value="user">User</option>
            </select>
          </label>
        </div>

        <div style={{ flex: "0 0 130px" }}>
          <label style={labelStyle}>
            Min. likes
            <input
              style={{ ...inputStyle, width: "100%", marginTop: 4 }}
              type="number"
              min={0}
              value={minLikes}
              onChange={(e) => updateParam("minLikes", e.target.value)}
            />
          </label>
        </div>

        <div style={{ flex: "0 0 160px" }}>
          <label style={labelStyle}>
            Author (id / me)
            <input
              style={{ ...inputStyle, width: "100%", marginTop: 4 }}
              type="text"
              value={authorId}
              onChange={(e) => updateParam("authorId", e.target.value)}
            />
          </label>
        </div>
      </div>

      <div style={rowStyle}>
        <fieldset style={{ border: "none", padding: 0 }}>
          <legend style={{ ...labelStyle, marginBottom: 4 }}>Operators</legend>
          {["add", "sub", "mul", "div"].map((op) => (
            <label key={op} style={{ fontSize: 13, marginRight: 10 }}>
              <input
                type="checkbox"
                checked={selectedOps.includes(op)}
                onChange={() => toggleOperator(op)}
                style={{ marginRight: 4 }}
              />
              {op.toUpperCase()}
            </label>
          ))}
        </fieldset>

        <div style={{ flex: "0 0 160px" }}>
          <label style={labelStyle}>
            Sort by
            <select
              style={{ ...inputStyle, width: "100%", marginTop: 4 }}
              value={sort}
              onChange={(e) => updateParam("sort", e.target.value)}
            >
              <option value="recent">Most recent</option>
              <option value="likes">Most likes</option>
              <option value="difficulty">Difficulty (desc)</option>
              <option value="difficulty-asc">Difficulty (asc)</option>
              <option value="size">Size</option>
              {/* Future options: plays, solves */}
            </select>
          </label>
        </div>

        <div style={{ flex: "0 0 120px" }}>
          <label style={labelStyle}>
            Per page
            <input
              style={{ ...inputStyle, width: "100%", marginTop: 4 }}
              type="number"
              min={1}
              max={100}
              value={limit}
              onChange={(e) => updateParam("limit", e.target.value)}
            />
          </label>
        </div>

        <div style={{ flex: "0 0 auto", alignSelf: "flex-end" }}>
          <button
            type="button"
            onClick={clearFilters}
            style={{
              padding: "8px 12px",
              borderRadius: 8,
              border: "1px solid #d1d5db",
              background: "#fff",
              cursor: "pointer",
              fontSize: 13,
            }}
          >
            Clear filters
          </button>
        </div>
      </div>
    </section>
  );
}
